import LandingCTA from "./LandingCTA";
export default function Home() {
  return (
    <main className="min-h-screen bg-slate-50 px-6 py-20">
      <div className="mx-auto max-w-3xl">

        {/* HERO */}
        <section className="text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-slate-900 leading-tight">
            You’re not invisible.
            <br />
            You’re just not positioned.
          </h1>

          <p className="mt-6 text-lg text-slate-600">
            Generate high-authority LinkedIn posts from your freelance experience in seconds
          </p>

          <LandingCTA />
          <p className="mt-4 text-sm text-slate-500">
            Free during early access.
          </p>
        </section>

        {/* PAIN */}
        <section className="mt-20 text-center">
          <p className="text-xl text-slate-800 leading-relaxed">
            You post.
            <br />
            You get engagement.
            <br />
            No serious inquiries.
          </p>

          <p className="mt-10 text-slate-900 font-medium">
            Because authority isn’t created by volume.
            <br />
            It’s created by positioning.
          </p>
        </section>

        {/* PROOF */}
        <section className="mt-24">
          <h2 className="text-2xl font-semibold text-slate-900 text-center">
            Example of a post generated by Prompta Flow
          </h2>

          <div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <p className="text-slate-800 whitespace-pre-line leading-relaxed">
{`Posting consistently isn’t building authority.

Last month, a freelancer told me,
“I’m getting engagement. But no serious inquiries.”

His posts were educational.
Well-written.
Safe.

But they could’ve been written by anyone in his niche.

Authority isn’t created by visibility.
It’s created by distinct positioning.

When content feels interchangeable,
clients don’t feel compelled.

I don’t work with freelancers chasing engagement.

If you want inbound clients,
your positioning needs tension.`}
</p>
          </div>
        </section>

        {/* DIFFERENTIATION */}
        <section className="mt-24 text-center">
          <p className="text-slate-600">
            Not templates.
            <br />
            Not engagement hacks.
            <br />
            Not generic AI content.
          </p>

          <p className="mt-8 text-slate-900 font-medium">
            A positioning engine for skilled freelancers.
          </p>
        </section>

        {/* FINAL CTA */}
        <section className="mt-24 text-center">
          <LandingCTA />
        </section>

      </div>
    </main>
  );
}